package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AgrAgremiacoescarn generated by hbm2java
 */
@Entity
@Table(name = "agr_agremiacoescarn", catalog = "opendata")
public class AgrAgremiacoescarn implements java.io.Serializable {

	private int codigo;
	private String modalidade;
	private String nome;
	private String tipoSede;
	private String dataFundacao;
	private String cnpj;
	private String bairro;
	private String cidade;
	private String rpa;
	private String uf;
	private String filiacao;

	public AgrAgremiacoescarn() {
	}

	public AgrAgremiacoescarn(int codigo, String modalidade, String nome) {
		this.codigo = codigo;
		this.modalidade = modalidade;
		this.nome = nome;
	}

	public AgrAgremiacoescarn(int codigo, String modalidade, String nome,
			String tipoSede, String dataFundacao, String cnpj, String bairro,
			String cidade, String rpa, String uf, String filiacao) {
		this.codigo = codigo;
		this.modalidade = modalidade;
		this.nome = nome;
		this.tipoSede = tipoSede;
		this.dataFundacao = dataFundacao;
		this.cnpj = cnpj;
		this.bairro = bairro;
		this.cidade = cidade;
		this.rpa = rpa;
		this.uf = uf;
		this.filiacao = filiacao;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "modalidade", nullable = false)
	public String getModalidade() {
		return this.modalidade;
	}

	public void setModalidade(String modalidade) {
		this.modalidade = modalidade;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "tipo_sede")
	public String getTipoSede() {
		return this.tipoSede;
	}

	public void setTipoSede(String tipoSede) {
		this.tipoSede = tipoSede;
	}

	@Column(name = "data_fundacao")
	public String getDataFundacao() {
		return this.dataFundacao;
	}

	public void setDataFundacao(String dataFundacao) {
		this.dataFundacao = dataFundacao;
	}

	@Column(name = "cnpj")
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "bairro")
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade")
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "rpa")
	public String getRpa() {
		return this.rpa;
	}

	public void setRpa(String rpa) {
		this.rpa = rpa;
	}

	@Column(name = "uf")
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "filiacao")
	public String getFiliacao() {
		return this.filiacao;
	}

	public void setFiliacao(String filiacao) {
		this.filiacao = filiacao;
	}

}
