package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BarBaresrecife generated by hbm2java
 */
@Entity
@Table(name = "bar_baresrecife", catalog = "opendata")
public class BarBaresrecife implements java.io.Serializable {

	private BarBaresrecifeId id;

	public BarBaresrecife() {
	}

	public BarBaresrecife(BarBaresrecifeId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nome", column = @Column(name = "nome", nullable = false)),
			@AttributeOverride(name = "endereco", column = @Column(name = "endereco", nullable = false)),
			@AttributeOverride(name = "telefone", column = @Column(name = "telefone", nullable = false)),
			@AttributeOverride(name = "especialidade", column = @Column(name = "especialidade")),
			@AttributeOverride(name = "site", column = @Column(name = "site")),
			@AttributeOverride(name = "email", column = @Column(name = "email")),
			@AttributeOverride(name = "column7", column = @Column(name = "column_7")) })
	public BarBaresrecifeId getId() {
		return this.id;
	}

	public void setId(BarBaresrecifeId id) {
		this.id = id;
	}

}
