package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtmgranderecifeRuasparadasonibusDadoId generated by hbm2java
 */
@Embeddable
public class CtmgranderecifeRuasparadasonibusDadoId implements
		java.io.Serializable {

	private String codigoDaParada;
	private String logradouro;
	private String bairro;
	private String cidade;
	private String latitude;
	private String longitude;

	public CtmgranderecifeRuasparadasonibusDadoId() {
	}

	public CtmgranderecifeRuasparadasonibusDadoId(String codigoDaParada,
			String logradouro, String bairro, String cidade, String latitude,
			String longitude) {
		this.codigoDaParada = codigoDaParada;
		this.logradouro = logradouro;
		this.bairro = bairro;
		this.cidade = cidade;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Column(name = "codigo_da_parada")
	public String getCodigoDaParada() {
		return this.codigoDaParada;
	}

	public void setCodigoDaParada(String codigoDaParada) {
		this.codigoDaParada = codigoDaParada;
	}

	@Column(name = "logradouro")
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "bairro")
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade")
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "latitude")
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude")
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtmgranderecifeRuasparadasonibusDadoId))
			return false;
		CtmgranderecifeRuasparadasonibusDadoId castOther = (CtmgranderecifeRuasparadasonibusDadoId) other;

		return ((this.getCodigoDaParada() == castOther.getCodigoDaParada()) || (this
				.getCodigoDaParada() != null
				&& castOther.getCodigoDaParada() != null && this
				.getCodigoDaParada().equals(castOther.getCodigoDaParada())))
				&& ((this.getLogradouro() == castOther.getLogradouro()) || (this
						.getLogradouro() != null
						&& castOther.getLogradouro() != null && this
						.getLogradouro().equals(castOther.getLogradouro())))
				&& ((this.getBairro() == castOther.getBairro()) || (this
						.getBairro() != null && castOther.getBairro() != null && this
						.getBairro().equals(castOther.getBairro())))
				&& ((this.getCidade() == castOther.getCidade()) || (this
						.getCidade() != null && castOther.getCidade() != null && this
						.getCidade().equals(castOther.getCidade())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this
						.getLatitude() != null
						&& castOther.getLatitude() != null && this
						.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this
						.getLongitude() != null
						&& castOther.getLongitude() != null && this
						.getLongitude().equals(castOther.getLongitude())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoDaParada() == null ? 0 : this.getCodigoDaParada()
						.hashCode());
		result = 37
				* result
				+ (getLogradouro() == null ? 0 : this.getLogradouro()
						.hashCode());
		result = 37 * result
				+ (getBairro() == null ? 0 : this.getBairro().hashCode());
		result = 37 * result
				+ (getCidade() == null ? 0 : this.getCidade().hashCode());
		result = 37 * result
				+ (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result
				+ (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		return result;
	}

}
