package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CtmgranderecifeRuasparadasonibusDado generated by hbm2java
 */
@Entity
@Table(name = "ctmgranderecife_ruasparadasonibus_dado", catalog = "opendata")
public class CtmgranderecifeRuasparadasonibusDado implements
		java.io.Serializable {

	private CtmgranderecifeRuasparadasonibusDadoId id;

	public CtmgranderecifeRuasparadasonibusDado() {
	}

	public CtmgranderecifeRuasparadasonibusDado(
			CtmgranderecifeRuasparadasonibusDadoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoDaParada", column = @Column(name = "codigo_da_parada")),
			@AttributeOverride(name = "logradouro", column = @Column(name = "logradouro")),
			@AttributeOverride(name = "bairro", column = @Column(name = "bairro")),
			@AttributeOverride(name = "cidade", column = @Column(name = "cidade")),
			@AttributeOverride(name = "latitude", column = @Column(name = "latitude")),
			@AttributeOverride(name = "longitude", column = @Column(name = "longitude")) })
	public CtmgranderecifeRuasparadasonibusDadoId getId() {
		return this.id;
	}

	public void setId(CtmgranderecifeRuasparadasonibusDadoId id) {
		this.id = id;
	}

}
