package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtmgranderecifeLinhaparadatrajetoDadoId generated by hbm2java
 */
@Embeddable
public class CtmgranderecifeLinhaparadatrajetoDadoId implements
		java.io.Serializable {

	private String nomeLinha;
	private String latitude;
	private String longitude;
	private String codigoSentido;
	private String nomeItinerario;
	private String itinerarioProvisorioAPartirDe;
	private String itinerarioProvisorioDataInicio;
	private String itinerarioProvisorioDataFim;
	private String codigoParada;
	private String logradouro;
	private String bairro;
	private String sentido;
	private String ordemTpr;
	private String ordemPrt;
	private String codigoLinha;

	public CtmgranderecifeLinhaparadatrajetoDadoId() {
	}

	public CtmgranderecifeLinhaparadatrajetoDadoId(String nomeLinha,
			String latitude, String longitude, String codigoSentido,
			String nomeItinerario, String itinerarioProvisorioAPartirDe,
			String itinerarioProvisorioDataInicio,
			String itinerarioProvisorioDataFim, String codigoParada,
			String logradouro, String bairro, String sentido, String ordemTpr,
			String ordemPrt, String codigoLinha) {
		this.nomeLinha = nomeLinha;
		this.latitude = latitude;
		this.longitude = longitude;
		this.codigoSentido = codigoSentido;
		this.nomeItinerario = nomeItinerario;
		this.itinerarioProvisorioAPartirDe = itinerarioProvisorioAPartirDe;
		this.itinerarioProvisorioDataInicio = itinerarioProvisorioDataInicio;
		this.itinerarioProvisorioDataFim = itinerarioProvisorioDataFim;
		this.codigoParada = codigoParada;
		this.logradouro = logradouro;
		this.bairro = bairro;
		this.sentido = sentido;
		this.ordemTpr = ordemTpr;
		this.ordemPrt = ordemPrt;
		this.codigoLinha = codigoLinha;
	}

	@Column(name = "NOME_LINHA")
	public String getNomeLinha() {
		return this.nomeLinha;
	}

	public void setNomeLinha(String nomeLinha) {
		this.nomeLinha = nomeLinha;
	}

	@Column(name = "LATITUDE")
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "LONGITUDE")
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "CODIGO_SENTIDO")
	public String getCodigoSentido() {
		return this.codigoSentido;
	}

	public void setCodigoSentido(String codigoSentido) {
		this.codigoSentido = codigoSentido;
	}

	@Column(name = "NOME_ITINERARIO")
	public String getNomeItinerario() {
		return this.nomeItinerario;
	}

	public void setNomeItinerario(String nomeItinerario) {
		this.nomeItinerario = nomeItinerario;
	}

	@Column(name = "ITINERARIO_PROVISORIO_A_PARTIR_DE")
	public String getItinerarioProvisorioAPartirDe() {
		return this.itinerarioProvisorioAPartirDe;
	}

	public void setItinerarioProvisorioAPartirDe(
			String itinerarioProvisorioAPartirDe) {
		this.itinerarioProvisorioAPartirDe = itinerarioProvisorioAPartirDe;
	}

	@Column(name = "ITINERARIO_PROVISORIO_DATA_INICIO")
	public String getItinerarioProvisorioDataInicio() {
		return this.itinerarioProvisorioDataInicio;
	}

	public void setItinerarioProvisorioDataInicio(
			String itinerarioProvisorioDataInicio) {
		this.itinerarioProvisorioDataInicio = itinerarioProvisorioDataInicio;
	}

	@Column(name = "ITINERARIO_PROVISORIO_DATA_FIM")
	public String getItinerarioProvisorioDataFim() {
		return this.itinerarioProvisorioDataFim;
	}

	public void setItinerarioProvisorioDataFim(
			String itinerarioProvisorioDataFim) {
		this.itinerarioProvisorioDataFim = itinerarioProvisorioDataFim;
	}

	@Column(name = "CODIGO_PARADA")
	public String getCodigoParada() {
		return this.codigoParada;
	}

	public void setCodigoParada(String codigoParada) {
		this.codigoParada = codigoParada;
	}

	@Column(name = "LOGRADOURO")
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "BAIRRO")
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "SENTIDO")
	public String getSentido() {
		return this.sentido;
	}

	public void setSentido(String sentido) {
		this.sentido = sentido;
	}

	@Column(name = "ORDEM_TPR")
	public String getOrdemTpr() {
		return this.ordemTpr;
	}

	public void setOrdemTpr(String ordemTpr) {
		this.ordemTpr = ordemTpr;
	}

	@Column(name = "ORDEM_PRT")
	public String getOrdemPrt() {
		return this.ordemPrt;
	}

	public void setOrdemPrt(String ordemPrt) {
		this.ordemPrt = ordemPrt;
	}

	@Column(name = "CODIGO_LINHA")
	public String getCodigoLinha() {
		return this.codigoLinha;
	}

	public void setCodigoLinha(String codigoLinha) {
		this.codigoLinha = codigoLinha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtmgranderecifeLinhaparadatrajetoDadoId))
			return false;
		CtmgranderecifeLinhaparadatrajetoDadoId castOther = (CtmgranderecifeLinhaparadatrajetoDadoId) other;

		return ((this.getNomeLinha() == castOther.getNomeLinha()) || (this
				.getNomeLinha() != null && castOther.getNomeLinha() != null && this
				.getNomeLinha().equals(castOther.getNomeLinha())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this
						.getLatitude() != null
						&& castOther.getLatitude() != null && this
						.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this
						.getLongitude() != null
						&& castOther.getLongitude() != null && this
						.getLongitude().equals(castOther.getLongitude())))
				&& ((this.getCodigoSentido() == castOther.getCodigoSentido()) || (this
						.getCodigoSentido() != null
						&& castOther.getCodigoSentido() != null && this
						.getCodigoSentido()
						.equals(castOther.getCodigoSentido())))
				&& ((this.getNomeItinerario() == castOther.getNomeItinerario()) || (this
						.getNomeItinerario() != null
						&& castOther.getNomeItinerario() != null && this
						.getNomeItinerario().equals(
								castOther.getNomeItinerario())))
				&& ((this.getItinerarioProvisorioAPartirDe() == castOther
						.getItinerarioProvisorioAPartirDe()) || (this
						.getItinerarioProvisorioAPartirDe() != null
						&& castOther.getItinerarioProvisorioAPartirDe() != null && this
						.getItinerarioProvisorioAPartirDe().equals(
								castOther.getItinerarioProvisorioAPartirDe())))
				&& ((this.getItinerarioProvisorioDataInicio() == castOther
						.getItinerarioProvisorioDataInicio()) || (this
						.getItinerarioProvisorioDataInicio() != null
						&& castOther.getItinerarioProvisorioDataInicio() != null && this
						.getItinerarioProvisorioDataInicio().equals(
								castOther.getItinerarioProvisorioDataInicio())))
				&& ((this.getItinerarioProvisorioDataFim() == castOther
						.getItinerarioProvisorioDataFim()) || (this
						.getItinerarioProvisorioDataFim() != null
						&& castOther.getItinerarioProvisorioDataFim() != null && this
						.getItinerarioProvisorioDataFim().equals(
								castOther.getItinerarioProvisorioDataFim())))
				&& ((this.getCodigoParada() == castOther.getCodigoParada()) || (this
						.getCodigoParada() != null
						&& castOther.getCodigoParada() != null && this
						.getCodigoParada().equals(castOther.getCodigoParada())))
				&& ((this.getLogradouro() == castOther.getLogradouro()) || (this
						.getLogradouro() != null
						&& castOther.getLogradouro() != null && this
						.getLogradouro().equals(castOther.getLogradouro())))
				&& ((this.getBairro() == castOther.getBairro()) || (this
						.getBairro() != null && castOther.getBairro() != null && this
						.getBairro().equals(castOther.getBairro())))
				&& ((this.getSentido() == castOther.getSentido()) || (this
						.getSentido() != null && castOther.getSentido() != null && this
						.getSentido().equals(castOther.getSentido())))
				&& ((this.getOrdemTpr() == castOther.getOrdemTpr()) || (this
						.getOrdemTpr() != null
						&& castOther.getOrdemTpr() != null && this
						.getOrdemTpr().equals(castOther.getOrdemTpr())))
				&& ((this.getOrdemPrt() == castOther.getOrdemPrt()) || (this
						.getOrdemPrt() != null
						&& castOther.getOrdemPrt() != null && this
						.getOrdemPrt().equals(castOther.getOrdemPrt())))
				&& ((this.getCodigoLinha() == castOther.getCodigoLinha()) || (this
						.getCodigoLinha() != null
						&& castOther.getCodigoLinha() != null && this
						.getCodigoLinha().equals(castOther.getCodigoLinha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNomeLinha() == null ? 0 : this.getNomeLinha().hashCode());
		result = 37 * result
				+ (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result
				+ (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		result = 37
				* result
				+ (getCodigoSentido() == null ? 0 : this.getCodigoSentido()
						.hashCode());
		result = 37
				* result
				+ (getNomeItinerario() == null ? 0 : this.getNomeItinerario()
						.hashCode());
		result = 37
				* result
				+ (getItinerarioProvisorioAPartirDe() == null ? 0 : this
						.getItinerarioProvisorioAPartirDe().hashCode());
		result = 37
				* result
				+ (getItinerarioProvisorioDataInicio() == null ? 0 : this
						.getItinerarioProvisorioDataInicio().hashCode());
		result = 37
				* result
				+ (getItinerarioProvisorioDataFim() == null ? 0 : this
						.getItinerarioProvisorioDataFim().hashCode());
		result = 37
				* result
				+ (getCodigoParada() == null ? 0 : this.getCodigoParada()
						.hashCode());
		result = 37
				* result
				+ (getLogradouro() == null ? 0 : this.getLogradouro()
						.hashCode());
		result = 37 * result
				+ (getBairro() == null ? 0 : this.getBairro().hashCode());
		result = 37 * result
				+ (getSentido() == null ? 0 : this.getSentido().hashCode());
		result = 37 * result
				+ (getOrdemTpr() == null ? 0 : this.getOrdemTpr().hashCode());
		result = 37 * result
				+ (getOrdemPrt() == null ? 0 : this.getOrdemPrt().hashCode());
		result = 37
				* result
				+ (getCodigoLinha() == null ? 0 : this.getCodigoLinha()
						.hashCode());
		return result;
	}

}
