package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtmgranderecifeTarifalinhaempresaDadoId generated by hbm2java
 */
@Embeddable
public class CtmgranderecifeTarifalinhaempresaDadoId implements
		java.io.Serializable {

	private String codigoLinha;
	private String nomeLinha;
	private String nomeEmpresa;
	private String sigla;
	private String valor;

	public CtmgranderecifeTarifalinhaempresaDadoId() {
	}

	public CtmgranderecifeTarifalinhaempresaDadoId(String codigoLinha,
			String nomeLinha, String nomeEmpresa, String sigla, String valor) {
		this.codigoLinha = codigoLinha;
		this.nomeLinha = nomeLinha;
		this.nomeEmpresa = nomeEmpresa;
		this.sigla = sigla;
		this.valor = valor;
	}

	@Column(name = "CODIGO_LINHA")
	public String getCodigoLinha() {
		return this.codigoLinha;
	}

	public void setCodigoLinha(String codigoLinha) {
		this.codigoLinha = codigoLinha;
	}

	@Column(name = "NOME_LINHA")
	public String getNomeLinha() {
		return this.nomeLinha;
	}

	public void setNomeLinha(String nomeLinha) {
		this.nomeLinha = nomeLinha;
	}

	@Column(name = "NOME_EMPRESA")
	public String getNomeEmpresa() {
		return this.nomeEmpresa;
	}

	public void setNomeEmpresa(String nomeEmpresa) {
		this.nomeEmpresa = nomeEmpresa;
	}

	@Column(name = "SIGLA")
	public String getSigla() {
		return this.sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	@Column(name = "VALOR")
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtmgranderecifeTarifalinhaempresaDadoId))
			return false;
		CtmgranderecifeTarifalinhaempresaDadoId castOther = (CtmgranderecifeTarifalinhaempresaDadoId) other;

		return ((this.getCodigoLinha() == castOther.getCodigoLinha()) || (this
				.getCodigoLinha() != null && castOther.getCodigoLinha() != null && this
				.getCodigoLinha().equals(castOther.getCodigoLinha())))
				&& ((this.getNomeLinha() == castOther.getNomeLinha()) || (this
						.getNomeLinha() != null
						&& castOther.getNomeLinha() != null && this
						.getNomeLinha().equals(castOther.getNomeLinha())))
				&& ((this.getNomeEmpresa() == castOther.getNomeEmpresa()) || (this
						.getNomeEmpresa() != null
						&& castOther.getNomeEmpresa() != null && this
						.getNomeEmpresa().equals(castOther.getNomeEmpresa())))
				&& ((this.getSigla() == castOther.getSigla()) || (this
						.getSigla() != null && castOther.getSigla() != null && this
						.getSigla().equals(castOther.getSigla())))
				&& ((this.getValor() == castOther.getValor()) || (this
						.getValor() != null && castOther.getValor() != null && this
						.getValor().equals(castOther.getValor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigoLinha() == null ? 0 : this.getCodigoLinha()
						.hashCode());
		result = 37 * result
				+ (getNomeLinha() == null ? 0 : this.getNomeLinha().hashCode());
		result = 37
				* result
				+ (getNomeEmpresa() == null ? 0 : this.getNomeEmpresa()
						.hashCode());
		result = 37 * result
				+ (getSigla() == null ? 0 : this.getSigla().hashCode());
		result = 37 * result
				+ (getValor() == null ? 0 : this.getValor().hashCode());
		return result;
	}

}
