package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CtmgranderecifeTarifalinhaempresaDado generated by hbm2java
 */
@Entity
@Table(name = "ctmgranderecife_tarifalinhaempresa_dado", catalog = "opendata")
public class CtmgranderecifeTarifalinhaempresaDado implements
		java.io.Serializable {

	private CtmgranderecifeTarifalinhaempresaDadoId id;

	public CtmgranderecifeTarifalinhaempresaDado() {
	}

	public CtmgranderecifeTarifalinhaempresaDado(
			CtmgranderecifeTarifalinhaempresaDadoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoLinha", column = @Column(name = "CODIGO_LINHA")),
			@AttributeOverride(name = "nomeLinha", column = @Column(name = "NOME_LINHA")),
			@AttributeOverride(name = "nomeEmpresa", column = @Column(name = "NOME_EMPRESA")),
			@AttributeOverride(name = "sigla", column = @Column(name = "SIGLA")),
			@AttributeOverride(name = "valor", column = @Column(name = "VALOR")) })
	public CtmgranderecifeTarifalinhaempresaDadoId getId() {
		return this.id;
	}

	public void setId(CtmgranderecifeTarifalinhaempresaDadoId id) {
		this.id = id;
	}

}
