package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FeiFeiraslivresId generated by hbm2java
 */
@Embeddable
public class FeiFeiraslivresId implements java.io.Serializable {

	private String nome;
	private String localizaO;
	private String dias;
	private String horRio;
	private String observaO;
	private String latitude;
	private String longitude;

	public FeiFeiraslivresId() {
	}

	public FeiFeiraslivresId(String nome, String localizaO, String dias,
			String horRio, String latitude, String longitude) {
		this.nome = nome;
		this.localizaO = localizaO;
		this.dias = dias;
		this.horRio = horRio;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public FeiFeiraslivresId(String nome, String localizaO, String dias,
			String horRio, String observaO, String latitude, String longitude) {
		this.nome = nome;
		this.localizaO = localizaO;
		this.dias = dias;
		this.horRio = horRio;
		this.observaO = observaO;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Column(name = "_nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "localiza_o", nullable = false)
	public String getLocalizaO() {
		return this.localizaO;
	}

	public void setLocalizaO(String localizaO) {
		this.localizaO = localizaO;
	}

	@Column(name = "dias", nullable = false)
	public String getDias() {
		return this.dias;
	}

	public void setDias(String dias) {
		this.dias = dias;
	}

	@Column(name = "hor_rio", nullable = false)
	public String getHorRio() {
		return this.horRio;
	}

	public void setHorRio(String horRio) {
		this.horRio = horRio;
	}

	@Column(name = "observa_o")
	public String getObservaO() {
		return this.observaO;
	}

	public void setObservaO(String observaO) {
		this.observaO = observaO;
	}

	@Column(name = "latitude", nullable = false)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FeiFeiraslivresId))
			return false;
		FeiFeiraslivresId castOther = (FeiFeiraslivresId) other;

		return ((this.getNome() == castOther.getNome()) || (this.getNome() != null
				&& castOther.getNome() != null && this.getNome().equals(
				castOther.getNome())))
				&& ((this.getLocalizaO() == castOther.getLocalizaO()) || (this
						.getLocalizaO() != null
						&& castOther.getLocalizaO() != null && this
						.getLocalizaO().equals(castOther.getLocalizaO())))
				&& ((this.getDias() == castOther.getDias()) || (this.getDias() != null
						&& castOther.getDias() != null && this.getDias()
						.equals(castOther.getDias())))
				&& ((this.getHorRio() == castOther.getHorRio()) || (this
						.getHorRio() != null && castOther.getHorRio() != null && this
						.getHorRio().equals(castOther.getHorRio())))
				&& ((this.getObservaO() == castOther.getObservaO()) || (this
						.getObservaO() != null
						&& castOther.getObservaO() != null && this
						.getObservaO().equals(castOther.getObservaO())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this
						.getLatitude() != null
						&& castOther.getLatitude() != null && this
						.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this
						.getLongitude() != null
						&& castOther.getLongitude() != null && this
						.getLongitude().equals(castOther.getLongitude())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNome() == null ? 0 : this.getNome().hashCode());
		result = 37 * result
				+ (getLocalizaO() == null ? 0 : this.getLocalizaO().hashCode());
		result = 37 * result
				+ (getDias() == null ? 0 : this.getDias().hashCode());
		result = 37 * result
				+ (getHorRio() == null ? 0 : this.getHorRio().hashCode());
		result = 37 * result
				+ (getObservaO() == null ? 0 : this.getObservaO().hashCode());
		result = 37 * result
				+ (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result
				+ (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		return result;
	}

}
