package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FeiFeiraslivres generated by hbm2java
 */
@Entity
@Table(name = "fei_feiraslivres", catalog = "opendata")
public class FeiFeiraslivres implements java.io.Serializable {

	private FeiFeiraslivresId id;

	public FeiFeiraslivres() {
	}

	public FeiFeiraslivres(FeiFeiraslivresId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nome", column = @Column(name = "_nome", nullable = false)),
			@AttributeOverride(name = "localizaO", column = @Column(name = "localiza_o", nullable = false)),
			@AttributeOverride(name = "dias", column = @Column(name = "dias", nullable = false)),
			@AttributeOverride(name = "horRio", column = @Column(name = "hor_rio", nullable = false)),
			@AttributeOverride(name = "observaO", column = @Column(name = "observa_o")),
			@AttributeOverride(name = "latitude", column = @Column(name = "latitude", nullable = false)),
			@AttributeOverride(name = "longitude", column = @Column(name = "longitude", nullable = false)) })
	public FeiFeiraslivresId getId() {
		return this.id;
	}

	public void setId(FeiFeiraslivresId id) {
		this.id = id;
	}

}
