package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MerMercadospublicos generated by hbm2java
 */
@Entity
@Table(name = "mer_mercadospublicos", catalog = "opendata")
public class MerMercadospublicos implements java.io.Serializable {

	private MerMercadospublicosId id;

	public MerMercadospublicos() {
	}

	public MerMercadospublicos(MerMercadospublicosId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nome", column = @Column(name = "_nome", nullable = false)),
			@AttributeOverride(name = "descricao", column = @Column(name = "descricao", nullable = false, length = 65535)),
			@AttributeOverride(name = "bairro", column = @Column(name = "bairro", nullable = false)),
			@AttributeOverride(name = "latitude", column = @Column(name = "latitude", nullable = false)),
			@AttributeOverride(name = "longitude", column = @Column(name = "longitude", nullable = false)) })
	public MerMercadospublicosId getId() {
		return this.id;
	}

	public void setId(MerMercadospublicosId id) {
		this.id = id;
	}

}
