package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ShoShopping generated by hbm2java
 */
@Entity
@Table(name = "sho_shopping", catalog = "opendata")
public class ShoShopping implements java.io.Serializable {

	private ShoShoppingId id;

	public ShoShopping() {
	}

	public ShoShopping(ShoShoppingId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nome", column = @Column(name = "_nome", nullable = false)),
			@AttributeOverride(name = "descricao", column = @Column(name = "descricao", nullable = false, length = 65535)),
			@AttributeOverride(name = "bairro", column = @Column(name = "bairro", nullable = false)),
			@AttributeOverride(name = "logradouro", column = @Column(name = "logradouro", nullable = false)),
			@AttributeOverride(name = "latitude", column = @Column(name = "latitude", nullable = false)),
			@AttributeOverride(name = "longitude", column = @Column(name = "longitude", nullable = false)),
			@AttributeOverride(name = "telefone", column = @Column(name = "telefone", nullable = false)),
			@AttributeOverride(name = "site", column = @Column(name = "site", nullable = false)),
			@AttributeOverride(name = "funcionamento", column = @Column(name = "funcionamento", nullable = false)),
			@AttributeOverride(name = "funcionamentodomingo", column = @Column(name = "funcionamentodomingo", nullable = false)) })
	public ShoShoppingId getId() {
		return this.id;
	}

	public void setId(ShoShoppingId id) {
		this.id = id;
	}

}
