package opendata.business;

// Generated 01/12/2013 11:24:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeaTeatrosId generated by hbm2java
 */
@Embeddable
public class TeaTeatrosId implements java.io.Serializable {

	private String nome;
	private String descricao;
	private String bairro;
	private String logradouro;
	private String telefone;
	private String latitude;
	private String longitude;

	public TeaTeatrosId() {
	}

	public TeaTeatrosId(String nome, String bairro, String logradouro,
			String telefone, String latitude, String longitude) {
		this.nome = nome;
		this.bairro = bairro;
		this.logradouro = logradouro;
		this.telefone = telefone;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public TeaTeatrosId(String nome, String descricao, String bairro,
			String logradouro, String telefone, String latitude,
			String longitude) {
		this.nome = nome;
		this.descricao = descricao;
		this.bairro = bairro;
		this.logradouro = logradouro;
		this.telefone = telefone;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Column(name = "nome", nullable = false)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao", length = 65535)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "bairro", nullable = false)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "logradouro", nullable = false)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "telefone", nullable = false)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "latitude", nullable = false)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeaTeatrosId))
			return false;
		TeaTeatrosId castOther = (TeaTeatrosId) other;

		return ((this.getNome() == castOther.getNome()) || (this.getNome() != null
				&& castOther.getNome() != null && this.getNome().equals(
				castOther.getNome())))
				&& ((this.getDescricao() == castOther.getDescricao()) || (this
						.getDescricao() != null
						&& castOther.getDescricao() != null && this
						.getDescricao().equals(castOther.getDescricao())))
				&& ((this.getBairro() == castOther.getBairro()) || (this
						.getBairro() != null && castOther.getBairro() != null && this
						.getBairro().equals(castOther.getBairro())))
				&& ((this.getLogradouro() == castOther.getLogradouro()) || (this
						.getLogradouro() != null
						&& castOther.getLogradouro() != null && this
						.getLogradouro().equals(castOther.getLogradouro())))
				&& ((this.getTelefone() == castOther.getTelefone()) || (this
						.getTelefone() != null
						&& castOther.getTelefone() != null && this
						.getTelefone().equals(castOther.getTelefone())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this
						.getLatitude() != null
						&& castOther.getLatitude() != null && this
						.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this
						.getLongitude() != null
						&& castOther.getLongitude() != null && this
						.getLongitude().equals(castOther.getLongitude())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNome() == null ? 0 : this.getNome().hashCode());
		result = 37 * result
				+ (getDescricao() == null ? 0 : this.getDescricao().hashCode());
		result = 37 * result
				+ (getBairro() == null ? 0 : this.getBairro().hashCode());
		result = 37
				* result
				+ (getLogradouro() == null ? 0 : this.getLogradouro()
						.hashCode());
		result = 37 * result
				+ (getTelefone() == null ? 0 : this.getTelefone().hashCode());
		result = 37 * result
				+ (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result
				+ (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		return result;
	}

}
